require("nvim.plugins.config.onedarkpro")
-- require("nvim.plugins.config.onedark")
require("nvim.plugins.config.treesitter")
require("nvim.plugins.config.lualine")
require("nvim.plugins.config.bufferline")
require("nvim.plugins.config.nvimtree")
require("nvim.plugins.config.telescope")
require("nvim.plugins.config.cmp")
require("nvim.plugins.config.lsp")
require("nvim.plugins.config.autopairs")
require("nvim.plugins.config.comment")
require("nvim.plugins.config.gitsigns")
require("nvim.plugins.config.indentline")
require("nvim.plugins.config.presence")
